x<-read.table("Downloads/household_power_consumption.txt",header = TRUE,sep = ";",dec = ".",stringsAsFactors = FALSE)
x$Date <- as.Date(x$Date,"%d/%m/%Y")
sub <- x[x$Date>=as.Date("01/02/2007","%d/%m/%Y") & x$Date<=as.Date("02/02/2007","%d/%m/%Y"),]

datetime <- strptime(paste(sub$Date, sub$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
global <- as.numeric(sub$Global_active_power)
globalreact <- as.numeric(sub$Global_reactive_power)
volt <- as.numeric(sub$Voltage)
sub_met1 <- as.numeric(sub$Sub_metering_1)
sub_met2 <- as.numeric(sub$Sub_metering_2)
sub_met3 <- as.numeric(sub$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(datetime, global, type="l", xlab="", ylab="Global Active Power", cex=0.22)
plot(datetime, volt, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, sub_met1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, sub_met2, type="l", col="red")
lines(datetime, sub_met3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.8, col=c("black", "red", "blue"), bty = "o")
plot(datetime, globalreact, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()